### ISSUE TITLE
How to build the system_update.zip file

### ISSUE THREAD

**Issue by Slayess** [seaky/nspanel_pro_roottool_apk#2]
Hello,

Could you please provide me with some details about the method to build the file system_update.zip ? I installed all Apps on one device, I would like to backup an system image to deploy on the rest of the devices.

Thanks in advance for your help.

**Comment by seaky** [comment]
Hmm its a bit tricky u need for example the rkDumper
https://xdaforums.com/t/tool-rkdumper-utility-for-backup-firmware-of-rockchips-devices.2915363/
But this device has the Rockchip px30 chip and you have to tweak the usb driver a bit

And the Rockchip AndroidTool which can upload the full dump to the device but be aware its raw chip flasher so you can brick your device easily

**Comment by Slayess** [comment]
Thanks for your reply, I'll search on this way ;)
